### ISSUE TITLE
Browse button doesn't seem to work

### ISSUE THREAD

**Issue by LukeSaward1** [Eddio0141/UniTAS#132]
Game: **Do It For Me**
Unity Version: **2017.4.10f1**
Game Build Type: **Mono**
Operating system: **Windows 11**
BepinEx version: **5.4.20**

**Comment by Eddio0141** [comment]
Hiya, currently the browse button doesn't function because I haven't implemented it yet, but manually inserting the path in the text box works
Planning to fix the issue in #114
