### ISSUE TITLE
Failed to parse movie: Missing script

### ISSUE THREAD

**Issue by LukeSaward1** [Eddio0141/UniTAS#139]
Game: **Do It For Me**
Unity Version: **2017.4.10f1**
Game Build Type: **Mono**
Operating system: **Windows 11**
BepinEx version: **5.4.20**
UniTAS version: **0.2.0**
Set up tool version: **1.1.3**

Reproduction steps:
- Load movie.lua in UniTAS and the error should appear.

For example, this is how it looks for me:
![image](https://user-images.githubusercontent.com/55454721/222509696-a946c174-92ef-4574-a049-be37f584f89c.png)

Log:
``` 
[Info] Starting TAS movie...
[Error] Failed to run TAS movie
UniTAS.Plugin.Movie.Exceptions.ParseExceptions.MissingMovieScriptException: Failed to parse movie: Missing script
  at UniTAS.Plugin.Movie.Parsers.MovieParser.Parse (System.String input) [0x00000] in <filename unknown>:0 
  at UniTAS.Plugin.Movie.MovieRunner.RunFromInput (System.String input) [0x00000] in <filename unknown>:0 
```

Movie:
[movie.zip](https://github.com/Eddio0141/UniTAS/files/10874144/movie.zip)

**Comment by Eddio0141** [comment]
Hiya, make sure you add the .lua extension as well.
The error means it failed to find the file in that path you've entered

**Comment by LukeSaward1** [comment]
Loading it as `C:\Users\sawar\OneDrive\Desktop\movie.lua` gives me the same error.

**Comment by Eddio0141** [comment]
Can you try with the latest build (here)[https://github.com/Eddio0141/UniTAS/suites/11312862034/artifacts/580853956] or if you're using the set up tool, `unitas_setup_tool install --branch master`

**Comment by LukeSaward1** [comment]
It works 😄

**Comment by Eddio0141** [comment]
Glad I could help!, closing
