### ISSUE TITLE
60FPS movies whizz by

### ISSUE THREAD

**Issue by LukeSaward1** [Eddio0141/UniTAS#140]
Despite my MOVIE_CONFIG table being this:
```
MOVIE_CONFIG = {
    fps = 60
}
```
movies whizz by at the speed of light.

**Comment by Eddio0141** [comment]
So the fps config makes the game fps run at a fixed framerate, but the playback itself has no speedcap so it will always run as fast as your pc allows it

I'm planning to have a way to limit this playback speed

**Comment by Eddio0141** [comment]
I've added this in #142 
You can check out the build [here](https://github.com/Eddio0141/UniTAS/suites/11322156873/artifacts/581428692)
