### ISSUE TITLE
[Bug]: Do It For Me crashes with latest UniTAS release

### ISSUE THREAD

**Issue by LukeSaward1** [Eddio0141/UniTAS#274]
### What happened?

I installed UniTAS, launched Do It For Me and the game crashed/hung at a grey screen.

### What should have happened?

The game should load into the game's splash screen.

### UniTAS version

Latest main

### BepInEx version

v5.4.x

### Game name

[Do It For Me](https://lixiangames.itch.io/doitforme)

### Game build

Windows x64 - Mono

### How to reproduce

1. Install BepinEx v5.4.X to Do It For Me
2. Install UniTAS 0.5.1 to Do It For Me
3. Launch Do It For Me
4. Press `Play!`
5. Wait for the Made In Unity splash screen to go away and it should either crash or hang at the grey screen.

### Log output

[UniTAS.log](https://github.com/Eddio0141/UniTAS/files/12678797/UniTAS.log)

**Comment by Eddio0141** [comment]
I checked and it seems to work on my side
Can you check the game's `BepInEx/plugins` folder and remove UniTAS if its in there? That might be the problem since I've updated UniTAS to work only in `BepInEx/patchers` folder

**Comment by Eddio0141** [comment]
Also for moving in this game, you have to do `controller.axis` with "Horizontal" and 1 for right, -1 for left movement
For jumping, `controller.hold("Jump")` and `controller.release("Jump")`

**Comment by LukeSaward1** [comment]
> I checked and it seems to work on my side Can you check the game's `BepInEx/plugins` folder and remove UniTAS if its in there? That might be the problem since I've updated UniTAS to work only in `BepInEx/patchers` folder

I don't seem to have a plugins folder. This is my BepinEx folder structure:
![image](https://github.com/Eddio0141/UniTAS/assets/55454721/b45c78e7-56e6-4581-a202-9230a6201bdd)

**Comment by Eddio0141** [comment]
Ah yeah I remember UniTAS causing problems with that
Try this [latest fix](https://github.com/Eddio0141/UniTAS/suites/16408229907/artifacts/937493863)

**Comment by LukeSaward1** [comment]
Yep, seems to work perfectly fine with that artifact 😄

**Comment by Eddio0141** [comment]
Nice! Good luck on TASing
